spring:
  application:
    name: usuarios-api
  security:
    jwt:
      contraseniaSecreta: "clave-super-secreta-para-firmar-jwt-123456789"
      expiration: 3600000
  datasource:
    url: jdbc:mariadb://localhost:3306/perfulandia
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
  forward-headers-strategy: framework