server:
  port: 8888

spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: clientes-api
          uri: http://localhost:8082
          predicates:
            - Path=/api/cliente/**
          filters:
            - RewritePath=/api/cliente/(?<segment>.*), /api/cliente/${segment}

logging:
  level:
    root: INFO
    com.gateway.api_gateway_spring_boot: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG